version: "2"

services:
  limited_redis:
    container_name: limited_redis 
    image: registry.gitlab.com/qio/standard/redis:latest
    mem_limit: 30M
    cpu_shares: 70

# Do not forget that the only available 
# redis image is accessible with the following url:
#  registry.gitlab.com/qio/standard/redis:latest
